[[questions]]
type = "MultipleChoice"
prompt.prompt = """
If the `Drop` trait is implemented for a type in Rust, which other traits should
probably be implemented?
"""
prompt.distractors = [
"`Move`",
"`Copy`"
]
answer.answer = [
"`Clone`"
]
id = "cddc736a-b6c3-4f3f-a3a7-b42eb362d650"
