[book]
authors = ["Brown University Cognitive Engineering Lab"]
language = "en"
multilingual = false
src = "src"
title = "C++ to Rust Phrasebook"

[output.html]
additional-css = ["custom.css"]
additional-js = ["telemetry/dist/telemetry.iife.js"]
code.hidelines = {cpp = "$"}
fold.enable = true
fold.level = 1

[preprocessor.quiz]
initial-text = "Check your understanding"
fullscreen = true
