[book]
authors = ["Brown University Cognitive Engineering Lab"]
language = "en"
multilingual = false
src = "src"
title = "Rust Phrasebook for C++ Programmers"

[output.html]
additional-css = ["custom.css"]
code.hidelines = {cpp = "$"}

[preprocessor.quiz]