[book]
authors = ["Cognitive Engineering Lab"]
language = "en"
multilingual = false
src = "src"
title = "C++ to Rust Phrasebook"

[output.html]
additional-css = ["custom.css"]
additional-js = ["telemetry/dist/telemetry.iife.js"]
code.hidelines = {cpp = "$"}
fold.enable = true
fold.level = 1
git-repository-url = "https://github.com/cognitive-engineering-lab/crp"

[preprocessor.quiz]
initial-text = "Check your understanding"
fullscreen = true

# [output.linkcheck]
# warning-policy = "ignore"