[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which of the following is the most idiomatic translation of this C++ function
signature into a Rust function signature?

```cpp
#include <cstdint>

void splitAt(std::uint8_t *data,
             std::size_t dataSize,
             uint8_t **left,
             std::size_t *leftSize,
             uint8_t **right,
             std::size_t *rightSize);
```
"""
prompt.distractors = [
"""
```rust
pub fn split_at(
    data: &[u8],
    mid: usize,
    left: &mut &[u8],
    right: &mut &[u8],
);
```
""",
"""
```rust
fn split_at(
    data: &[u8],
    mid: usize,
    left: &mut &[u8],
    right: &mut &[u8],
) -> (usize, usize);
```
""",
"""
```rust
fn split_at(
    data: &[u8],
    mid: usize,
    remaining: &mut &[u8],
) -> &[u8];
```
"""
]
answer.answer = """
```rust
pub fn split_at(
    data: &[u8],
    mid: usize,
) -> (&[u8], &[u8]);
```
"""
id = "17e30276-7ebe-499e-b8b0-4acfb815feaa"
