[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which Rust program is the most idiomatic translation of the following C++
program?

```cpp
#include <cstdint>
#include <limits>

int main() {
  int64_t x(4294967296);

  if (std::numeric_limits<int32_t>::min() < x &&
      x < std::numeric_limits<int32_t>::max()) {
    int32_t y(x);
    // ...
  } else {
    // ...
  }
}
```
"""
prompt.distractors = [
"""
```rust
fn main() {
    let x = 4294967296i64;
    if Into::<i64>::into(i32::MIN) < x
        && x < Into::<i64>::into(i32::MAX)
    {
        let y = x as i32;
        // ...
    } else {
        // ...
    }
}
```
""",
"""
```rust
fn main() {
    let x = 4294967296i64;
    let y = x as i32;
    if y as i64 == x {
        // ...
    } else {
        // ...
    }
}
```
"""
]
answer.answer = """
```rust
use std::convert::TryInto;

fn main() {
    let x = 4294967296i64;

    match TryInto::<i32>::try_into(x) {
        Ok(y) => {
            // ...
        }
        Err(err) => {
            // ...
        }
    }
}
```
"""
id = "98badbec-d894-490a-929b-327021cda0c3"
