[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which of the following are true about the Rust `char` type.
"""
prompt.distractors = [
"""
It is equivalent to the C++ `wchar` type.
""",
"""
It is equivalent to the C++ `char` type.
""",
"""
It is equivalent to the C++ `char8_t` type.
""",
"""
It is equivalent to the C++ `int32_t` type.
""",
"""
It is 8 bits wide.
"""
]
answer.answer = [
"""
It is guaranteed in safe Rust to represent a valid Unicode scalar value.
""",
"""
It is 32 bits wide.
"""
]
id = "4fb18334-8405-438d-8d3e-859a8823bccf"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which of the following are true about `std::sync::Arc<T>`.
"""
prompt.distractors = [
"""
It provides thread-safe write access to a value of type `T`.
""",
"""
It can be empty (i.e., not own some value of type `T`).
"""
]
answer.answer = [
"""
It provides thread-safe read access to a value of type `T`.
""",
"""
It represents shared ownership of a value of type `T`.
"""
]
id = "5586766c-b5ce-4bea-b995-da0b3c548b0d"
